### ISSUE TITLE
Traductions grid no longer working

### ISSUE THREAD

**Issue by NVasse** [lexik/LexikTranslationBundle#290]
Hello,

I upgraded from 4.0.2 to 4.0.5 and I get this error when I go on the traductions grid :
> angular.js:9503 Error: [$injector:unpr] http://errors.angularjs.org/1.2.13/$injector/unpr?p0=%24httpParamSerializerProvider%20%3C-%20%24httpParamSerializer%20%3C-%20translationApiManager%20%3C-%20tableParamsManager
>     at angular.js:36
>     at angular.js:3556
>     at Object.c [as get] (angular.js:3683)
>     at angular.js:3561
>     at c (angular.js:3683)
>     at Object.d [as invoke] (angular.js:3710)
>     at angular.js:3562
>     at c (angular.js:3683)
>     at Object.d [as invoke] (angular.js:3710)
>     at angular.js:3562

And if I try to rollback to 4.0.2 I get :
> Type error: Argument 5 passed to Symfony\Bundle\FrameworkBundle\Translation\Translator::__construct() must be of the type array, object given, called in /private/var/www/Siqual/ahloet/var/cache/dev/appDevDebugProjectContainer.php on line 5870

I'm using Sf3.3

Thanks for your help.

**Comment by agatool** [comment]
@NVasse Have you found a solution ? Cause i'm exactly in the same case

**Comment by NVasse** [comment]
@agatool Not at all

**Comment by agatool** [comment]
I've tried to put back the former translation.js, the grid appears but not the others actions (update, delete) cause the csrf token is invalid...

**Comment by agatool** [comment]
@NVasse version 4.0.0 is working but its without csrf protection

**Comment by Getuser31** [comment]
Hello. Same issue here

As version 4.0.0 doesn't work with Symfony 3.3, for now it make impossible to access to the translation grid. 
Can someone have an idea on what's going wrong there?
Thx

**Comment by acidjames** [comment]
Hi Guys,

i've got this working on sf3.3. I suppose you are integrating LexikTranslation with your own website template.

Apparently, they refactored the twig blocks so everything has to be called and rendered where it's supposed to.

I've extended the original template by creating a layout file in 
`app/Resources/LexikTranslationBundle/views/layout.html.twig`
This is the only file needed to integrate in your design.


This is my layout. My original layout only has a title, css, javascript and page block, so you can easily adapt with your layout : 
```
{% extends 'AppBundle::layout.html.twig' %}

    {% block title %}{% block lexik_title %}{% endblock %}{% endblock %}

    {% block css %}
        {{ parent() }}
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ asset('bundles/lexiktranslation/ng-table/ng-table.min.css') }}">
    {% block lexik_stylesheets %}
    {% endblock lexik_stylesheets %}
    {% endblock %}

    {% block page %}
        {% block lexik_flash_message %}
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        {% set flashes = app.session.flashbag.all() %}
                        {% if flashes | length > 0 %}
                            {% for type, messages in flashes %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ type }}">{{ message }}</div>
                                {% endfor %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endblock lexik_flash_message %}

        {% block lexik_content '' %}
    {% endblock page %}

    {% block javascript %}
        {{ parent() }}
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.min.js"></script>
        <script src="{{ asset('bundles/lexiktranslation/ng-table/ng-table.min.js') }}"></script>
        {% block lexik_javascript_footer %}
        {% endblock %}
    {% endblock %}

```

**Comment by NVasse** [comment]
Thx @acidjames for pointing out the problem, I hadn't really look into it until now but I found out that we are using our own templates, which didn't use the same Angular version and didn't have the csrf.
