### PR TITLE
Fix issue with angularjs 1.8.x

### PR DESCRIPTION
**Pull request by raziel057**
The component doesn't works with AngularJs > 1.5.x:

The $http legacy promise methods success and error have been deprecated in 1.5.x and is removed in v1.6.0. 
So we got the following error: ``TypeError: $http.get(...).success is not a function``

See : https://code.angularjs.org/1.5.11/docs/api/ng/service/$http#get

As suggested we need to use the standard then method instead.

### CODE REVIEW

**Comment by raziel057** [comment]
Hi there,

I'm a bit confused that this PR is not yet accepted knowing that the component relay on angularJs 1.8 by default since commit https://github.com/lexik/LexikTranslationBundle/commit/ed737c50b913f41bcc3c293a19891dfbd49d0a47 

So currently it lead to JS errors related to ``translation.js`` when using angularJs > 1.6.0.

For the context:
image

Would it be possible to merge it in master and 6.0 branch?

**Comment by bartmcleod** [comment]
@raziel057 I simply didn't have time, it looks perfectly allright to me, there are conflicts though, is it possible this was already fixed when I did some frontend fixes for SF 7? Can you maybe solve the conflicts? And feel free to make a PR to the 6.0 branch as well.
